from collections import Counter

str='''
Key Achievements:One of my main goals during this internship at Škoda Auto was to enhance the usability and functionality of a Python-based testing application initially provided to me. The app, initially a complete shambles, suffered from poor coding practices and limited usability. Immediately recognizing the unenviable state it was in, I took the initiative to refactor the codebase thoroughly, applying precise coding standards to ensure readability and maintainability. By doing so, I effectively turned a thankless task into a rewarding project. Currently, the application is up and running, with additional features continuously expanding its capabilities. This turned out to be a lucrative improvement for internal efficiency, saving countless hours previously spent navigating mind-numbing bugs.
Challenges Faced: The biggest challenge was the looming deadline set early in the internship, combined with the poor initial state of the application. It threw me completely initially, as it required significant effort to untangle convoluted logic and unclear documentation. Despite moments when it felt like a real nightmare, my self-reliance and resourcefulness allowed me to overcome these issues by systematically debugging and incrementally updating each module. What initially seemed like a storm in a teacup became manageable through perseverance and structured planning.
Skills Developed: Throughout this internship, I considerably improved my Python programming skills, particularly in writing clean, efficient, and scalable code. My tough-minded approach allowed me to develop stronger problem-solving and debugging abilities. Furthermore, by effectively handling a dynamic and fast-moving project, I cultivated better time-management and organizational skills. The experience also allowed me to establish a good rapport with my colleagues, facilitating explicit communication within our close-knit team.
Areas for Improvement: Looking forward, I aim to further develop my expertise in advanced Python frameworks, enhancing my capacity to handle more complex application architectures. Additionally, I recognize the need to become more proficient in automated testing and continuous integration practices. My goals for the next cycle include mastering these areas to streamline development processes even more effectively.
Feedback and Support Needed: To achieve these improvements, I would greatly appreciate blunt, constructive criticism regarding my coding practices and advice on best practices for continuous integration. Access to targeted training sessions or mentorship in advanced Python development would further bolster my growth, ensuring I continue to be an achiever who knows this field inside out.
'''

counter = len(str.split()) 

print(counter)
